spring.application.name=almoxarifado-api

spring.datasource.url=jdbc:postgresql://trolley.proxy.rlwy.net:38589/railway
spring.datasource.username=postgres
spring.datasource.password=yeJktxPVVDqHrUReOjbRIseWOwQXXaHk

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true